FROM bitnami/spark
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.704/aws-java-sdk-bundle-1.11.704.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.704.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.0/spark-sql-kafka-0-10_2.12-3.3.0.jar --output /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.3.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.3.0/kafka-clients-3.3.0.jar --output /opt/bitnami/spark/jars/kafka-clients-3.3.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.0/hadoop-aws-3.2.0.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar 
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.3.0/spark-token-provider-kafka-0-10_2.12-3.3.0.jar --output /opt/bitnami/spark/jars/spark-token-provider-kafka-0-10_2.12-3.3.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.2/hadoop-client-runtime-3.3.2.jar --output /opt/bitnami/spark/jars/hadoop-client-runtime-3.3.2.jar
RUN curl https://repo1.maven.org/maven2/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar --output /opt/bitnami/spark/jars/unused-1.0.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.2/hadoop-client-api-3.3.2.jar --output /opt/bitnami/spark/jars/hadoop-client-api-3.3.2.jar
RUN curl https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar --output /opt/bitnami/spark/jars/snappy-java-1.1.8.4.jar
RUN curl https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar --output /opt/bitnami/spark/jars/slf4j-api-1.7.32.jar
RUN curl https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar --output /opt/bitnami/spark/jars/commons-logging-1.1.3.jar
RUN curl https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar --output /opt/bitnami/spark/jars/jsr305-3.0.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar --output /opt/bitnami/spark/jars/commons-pool2-2.11.1.jar
RUN curl https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar --output /opt/bitnami/spark/jars/zstd-jni-1.5.2-1.jar
RUN curl https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar --output /opt/bitnami/spark/jars/lz4-java-1.8.0.jar
